[package]
name = "rust-academy"
version = "0.1.0"
edition = "2021"

[dependencies]

# bring in the rippling-rust-academy crate
academy = { path = "../rippling-rust-academy" }

# other dependencies you're probably need
anyhow = "1.0.75"
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
time = { version = "0.3.29", features = ["serde"] }
async-trait = "0.1.73"
clap = { version = "4.4.6", features = ["derive"] }